<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAABgDAAC0YMsRNV5kmuGfaI5iHIXajqz0xzJ3Ymo9nuAxSj5TUg8IIIUw44XeYfyAr/FhCByHtdXwuYdNcR7b0GUdxx0312La9mw3LNzP4UoJhB21OnqaKh6Q6DFBejfPWMMwyszSLNyeqhk4p7ymJHRD5PvMytZB9ZJnarSuPJN31W+SqHSogqi0ztbd5ndItA7jp65d7KRkon6oOCU4uBUHce5P2IZGfu0KAY24FG19X4zFICCQVzYB7JHuJzasU9vA2zzrIMUU7KvWnhiutVwB+n1WkNfPQciMMyTe+Le5hCH/XEAWaeW3yrvasgJU0bZU0G6nqLjItM047q5gqSSQTQQ4Mo9kpaE3ISTQe5qb/ClUxjq3Oefu4QR/RfTIX6Ua4TC/6/VK6aOMRlH/x4s4Cn3xaZ2VTq5pjGVjlecUPAtsEP1mWJnuzg2wQe8pmG9/rQGsxwpu/K7lJXwIL+Sk8ie8aEH2Qh84lk/5Mp2vmogiwHGDbhCs1TVB4RRc+y+8MtJjiV+WEqXcp8jmKqIZMW41HydA9PR4s+Ef2TCDHdxZxGrZwhrD4vMG7jzL3PVklbrggwEKLHeSJAyFLc2/YsxiG9r3xwbsesP9F0jRrlYAg+tvCRbokNBSpqO3nD5WOpxmf8O0vy0OZZTJb64UGpFpebT1T8zI2qwB0nss9QoBHRFx+/6U11t2Vp/5KmyNE5aAND1KJb2j5L8XbiL2p8VHXgcmW/+EDLH7FAMwQsao1CGuF5/NkYGyR0vNlIE+hncn6DeFWFVGDgjQLVG7w3EuYCfUOjWbKlOBe4YqmE/rgQAym9BMTw105F/LlXVN6TUAB9I5q4TJgvazR2MVSZCrAgq7eu2KMcCGc8x3N1HvZK9yDnBhZ3ZWmhY5795Wv95ACk9dixBkkHvIgAtDJtuPh77+btX21RNE//Hu8lYqhVn4jshpVjljgIrWb/yF57K30qPQSWVOVqtQhqAgXJ9JMx/X7zgPlRANJsrbKVfKtCAnCZis2K24s/iGAts0UPZceNvYq2peQoDZU4MX2eGgOpQPFmXV10dKAAAAEAMAAIyLaqmAajj5FI19eqRlf8Ln2eWBQaPXtyx1gVCoF8eU752TbEEReem1OBMal7TPDC/lniOqI5ekyFJ3TL+v/Pahd5Uhrbpe2kP5JpRSrVGOPmLo5TeIPld/jnQEhCwJHmvsOM/XwLehe9Fd3GbCbPUbmRwoccuckMj99rkGP774Qw1ijcLDqQ1/MTIlij103h1WjctCvbVHDw2VRO4HybNBGDRwrXlaViNic+X5UrW6HXnbdsSsyyCux76ebqAWbwLH+7o3Fdam9tiDK0Po/aVgIrYhdfJJteCxUl2jSBJOPCJGloT+9PYUsc5i3wup4WjFERNiVCBkDvjNVEr3K/6j3N0tGNjONfhhXNpllx49keyvJDt2O8b4zBQuXP/qYLVlqPOAbuP4C58OirHQaCDZSTKqFjM3/TDNdLDJgCVs8lf84R+d/ed7SQ1xOl0vLVeSeY+n8jmQ91skPcxk8UmS4oBSs+We2tuGRDCXNDVrKnXg3zFAgLB8rjTnYM0SAw1t81jlDGaA9bQQ5UCYMCO9nyxlm7XMhM++n8MGRrGshBtoXphmCGLkDRWVYvgYQTAu1vANsL2mqHGfORo+545icokTpf+bihreJKGP8Ag1yv0FGW7nKfEc61yvu+5lzDIDzsYVegZgZ/Ok6/DMIMGSenYNkXQfqaToxdYcJzdWIxZexiJmcJIYn1njVap0LG8Dkv1Y3GKEwR1pCbPDV7TBhbNMmcNrXcPL9i2u4VRPCnRQdJknO0s/goCNV+SCVkIx6haOimx+psDiqjBlzZ9CizPB3J/zgawcLC61iuO0hZA7fD9PHYYmzqjLwl2uk5QES2hloJy2vGcpoK7jD5gYoWd++BqXoJtyEb/mUhUM7C3AWgYbIDa142besEG5OlwsuP7E2dUcBmna6dF+3o5GtpWz6QPqeUWW0j4XbNNvPrzj2lKe8Z9kFOxY6O1sT2u9TL3rcu+FQoXMm7Cg2o3opNyDvp+BqXOcHiA3EZvIS3kFhwPi81S+7nYuzFhvnbK0MF70RjKWWksOWyk0t4oAAAAA');
