<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAAGADAADdCUyjX5+dzTfd7d785E4bwBHMZI7Dzi6WUwi46JP/I+i/WmgaIVqXkU8HDR19sV9EGhVvi9RiuEd5AYLGV93/WzRpwKKJkhPft79MxZG9ddbfiz4wixRcPb9+udxjRrP/9NY9uci3/hvOQNmUw/YZijD8zWuUCLkmJn+ik/kzT9+mzwyvJTU0tmcYAb2xrLEsLsrjzvLAzQ0c9+xdPsMTB6HuJP9TPfjPz6hz1dw8aT07NEWUf52XqocWEtIgslSvUXqU3tyD64eWrrBO4Izi058imkt1VTcCCsk8jflCmFgsB+BC8sC12PecTeppGPpmMOvbv78oKSM1p2Z6JQ/NCQNA7lz0Y8l0+hKZ+qJ6BuEixZXG6bIJ8A2IWyJWqPXhSBWIpQrXJg+X1vdcBkhekn2A50peg4n250RSlabZnDgvMOi6IFZlph0X8Z5Hl9yIfwqDNELreK8bZeBuKJQ4RHZSfgFgphj9Q8WuN40K8Q1hJZ4VP3jsYbmBqCUTC7Dr4HnuCWQIQy+ICDerbFKx9zWRjn37Sr9O5cP/hoV6GUGjjDsMTqVfbzwWT5shXTsQRp7XwxlMlyzQGKSY0e52NGKnM1U/2LUGyeFjBLAk6Jlke+KNBWqydC388j7e5aNKvNqD+fZOPKssJU+VmVKAPX+UUdy3RP3A2TMA/JRyRPqdEx7lXmJDjzqDoAMxL+Ki/9nLLuZvZEpXKPslMklv5CYq4S65tIY+jElhUmWjTiPrl2qNjDZKGkraPi1PTTe3/dUpxNyvPm0ct6K3lY1wOX2y6Fv7xkp3+7mwKeoGdqwubmJ32kWlpAaRY6gRTp2t/eRKOaLiu8jcmRaHde4t4CUUFb6Y7AlZ9/GSz9uJUAz3ZK8AXbxGy+UTKQJAK7rSoN4RQel9qktsu9Zi48lmet3lV/vDJp3D4ErdyPUKRbqn8dnHVvKjhKp6m3Ik6OZvMK+mT6v7ARG3C+uSzlr9aXETXBVJNCDEZRuEStwhT3j6XNOgfCO4UXIB0FiWaFZYUgOVGjxIGzWIInCgby2Tbg8ylJLHjCKVODevKE2ctorXVcCf1HQ+zW6C/QtPY0GecKIC3+mR6X26OQ+7vfdf9uNwwLVD7u+G7zpLtA4+/WI73VK2WEUpbIs45FDjNulKAAAAaAMAAEMDOf9ogy/yz7ROngWoD1+VNzh0rbuRDmJJ8MVOBYaEHY1f/OBArewT5OfEEx4HIMfersrtVs4Cgg9lD2uxD/ddE2dqt0SyMx6eqvAbBOpg4NtxytBI9nZMzIL4GOBf5tvVIysBmOIH9QEZKxM7kGi9oMU//9IthJKA8DxBsnvldSYR68b5TTGKAvkaSVznQ2LQY0snjLoE/0xqddpit70swTm2p5jseKtFLYZKD1LiD2D+2lQtiY4y1eLvmRvJ1uRdQNn28ntTEaWtDp0qLClsS+H8FU1yTVgEY3f/svQ0+ho7Ttxr8k7KMp8g5z5j+eCfrF524n+CfkT8cSsFZ9944Lhth2qor2ePLo6EOvdSwg0z3VuvIFhAa5Qiqm7zQDYnQOyGjoJ/KlT8KItQTjD6o+Ct5f5z+aCgpGxiSKtWtWqcF3kXKf4+0NPvkSlsCKIsZ08+oDfeQid6MLScIiDkDFvoi2ukqnmyotHesOISYpcs3i3lBQrDxUXWCrb+JxTV/qqg+zf+2QS4P6dDBADsu9riNoYMMkeiAFuJDEvjhPPDvotZ58NJQ4Q01BzDwmvIIXPUp821B538TiH8cR7Jn2h1lZ0gJaI//rOCxOeazoWkLUGQc4J1MX3M1t0v/zd0RH2EpXCTMzzDrxc5KE9r2tjDBHh693Tjcis87XxLH0CHnOcy6RR2x/Sn6wsOk4ZHWkIu4/dtxlnJbKp/NVaB3Q/BxBlQyr9NCMSynUocRYAJ89uIMSJ7IO+8KQ+EI7TXOJ9EjgpMRaH802oxEWA6W44r7SoA5N7l9b+yXsD82jo3Rw4SfM4oUiQbbCV/WiKz+CX/pYz/SzFf1A4RAX+uuhD0ereA6J6KDiAjJJ2yERb60RHYICLk8+LTRdBZ0Rvr5PCgg4br93XbBTdj0t9GYBxCoD1qNTzgQ/YHDwU5Zo5CajJF8eRBDI2Pq1KivaEmRGYwmJMwxBSRjunFs0KtSqKH3n0GLYT/b5Ofg/QsvAkzkSHj0fVfiIsc3hrsW9E66Klkx6TGonk95IXlN0LBaDH2mNq+Oshfx9FCDSYRNUMmzlTuXBwPWvmnl3gpduGtx3GuBtGfiCYDElxjSSt6/HBICl+aQTFiyKwuMW1ByFGO32SYIMziSZfm5DFWtpNV15E2ubr6AAAAAA==');
