<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAAGADAACLfUY+Xwpjw+9YXAYk8xMQRQj5J///01GECKwVZ/UqIaDcrm/fckqsh/XvMSOex5SfrhP0AOoxK3LoiM6zNPHgdDRcF7V2O5sdHJt9FdwouxiJ4rr0107zHFkT+Fv6IzyBuTKRBCkkMtZmqWOH7a3Tb2LCmLSS7Z9039S/s2PYHr7Dmwmpb6J7aj5L7B49ZerUJ6SCIJKEmDuVu1NJoftXAqeZ6uxQyeEoC1lyisBD9ctgpRKsD0DRVz6PDLMV+0vJ0ei9YGvOUfcWCWYbBnOLhjLGJ/Pp7XJ+5Wx46lETYb2sIA//8DoEgH80pUG3AEEBB08tevpC/R4+Rzl71W+nz2Wo6t2Zu8ErZFUqyzYH2/cY4NQ3xO+ycIK4KAL5jug4a4yCA2X60gGVp9NpwU8bJsldlA7jUcUpZ+aCDc66vtnY96F/Q0XcnrwXdeYeRTE9H9sjLHun+UZHTecThCP1t8d1X2NW9eyFgj0SbBDuSQSgdzNPxNNor7CDJX9wk7ajdjhzApUFpyO/csi9PNHbadqHdF0mjMTb1N4Qiv1LHM0lTmvANsSbrr3BLfinaxvYdx68HmWouj3BPxn6BZ8FhWBaMl3AbdMK4HmqP1HEEtj9UemRZP/F81KcMXLel/DXN6JZk6S319PYA/N5v6XXZRE/Rf2w3kagHwoG+NeJzZ2KSCiZy+P3q6i2EhRCDDPJMzQ99r8L8AKDaFIrSdviCQlIpPsg/VPBO3Gku20lmYt3vciz1m0aRA8zTQnqdXHGDlQEO60LIN4asV+8y8Pt1GSnxeDrR6U8eOieS8Fo9l4MCeIYOyclb+CKExd+Q647B9aEUsLQHtsRpExC4SEmFvdz/CpoGIZuIFYgg3M5jPuaeAORg53EWOXmbubrfPFsqahEdZDphnIawjaR6MusxLiXeT0YcWh1XC6L4uND1I23lZHCMkEFxiBUb1JGBDANYIkY91TtCYPLeaWsFCaM9e2ZQMWSEJJg5bmAE0eFnbDzhiFiLiUO85O6iWBd0VooNe8IN50PcHfM/eaoVK+SCSR3N+GZR+EmNbhRQ71J73BGfOCJPqET3oaN5pmHr2TeLsMZ/FritQTVs24gZHi3LBG+EewcQO0SPMczjflx3LWan1sck86vWbZbyhqqH5dKAAAAYAMAAO5tXwTkjqjxE6W7lBYEvolT4Ye2YRKKgkZyq1MMT7oj2OMre42FMafJ+/3WmFs6HZujzptUVEvKNXTYkZ81zTnZM0Kys8FnpNkflFneEcy6dbDS1ieuVUNVznx7bSmS3TyPd0DIdJLiOZ84kmgYDjmfKVLPWlrk0gvxtE9+jVu7zdtK33QnOUa6vPxaWmaEIQvq8CmCLz01f2rE6gNC5/7a+WnuYyTjQgOyk+Q/j4D6/BIdGh8ht22feVrRXlpLn/5uE9DhoOLmqaGirYtlNjmADVhVchkX7Ejp6Xv+seL9BH8B1QOllwHWY19HYbmyRiCh+ORw1IL1NfDafHAnYd1XP1DJmE+EuVYVpTfkE0KALAIZVlt5d2ghiIXIsLtSR80GG5CeeEtouesQd677K30l/BpjDNCFSYJQN/G5C+iN+m4yQVYFQWJ5gx7A10TFJcWQM0MCwwy++R5NpHuQeSBM0KL6CXBaKCD6T+zn3AcpDmrWmqKUF3MLHvDaKSxcO8xJVSt0byiB9In0yfveHJLrjYOCWmKAZjg+r3E0BOwpwHBvzM0EYwBpeoUIPqpb82hJExQqckPTWLfemPeSVbqZiGf+iIqKNDwev24+4hDYx+DsLwXyYzOUvjmffZq6sp1g9bEe3sYliwhmOFx3boiXPtCH5hKCiHHx64NsftLeDWVzIgM0wqhVLbB32s7uafyaKxdKsQeqkK/RnWzEq2lungYpx10p5CbLqOLl320Hc8jVxB9lw8CrW4uFn27E46P2vTFvbcKxTlgNXfmlR/XlskHLi6O2ccohXi5CMsHknUxcPNBpfanxiGknnhf1G4YeEd3v6RoU1nJAgrSrgmPacGuMsvioS/njDPUpEwh3zS/8Kyx0wJBQwaC/Fzqz6lRU/DkZtIUWpElDxIj/LmslS7tv0CFiAwx+1W1CtFGwPEu/XsT7wSe546CO0j9vBfxcDQy4Pc8crsOIt+87tescVBFmnDhLhKKlcmOeTuiRFeTZfPYVvJjH9yqFj5ntpGPExg+eivXXepxIhCHW+1RvXF/6+9WlR/lBiAy/jJM/66hWMUrHFqmi+Jn+skVI//jJqs3c6tOC8BSDDqpxRwoA5mm1J3/DOejNnurNO4WEYSMbvK1bMSp62pBXPBRTrgAAAAA=');
