<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAAGgDAABdeyQnXrJ6E5v3FNFgYqT0N6UhtZL6ATIlEkiSJDT4jaM3WcBF/gF7/qvXS1Ifvm4dgCH3FuyY9kKgp7CmMoczqFt+U6a9uKL6SndpAT/WS426qUxsPhO16fYZtQZVdIqyhSkxivvRD3IUi+cMv14GXnSpdUuOndLbVSPsWO2vTmKAW3I2lp4p9al73eF79Fr4uvOpuydLRe5ywLa9TAr2wzb1o6K6SADyY2uENxoDT69UKavlnl49rVFn52EvStZhPge43L1NUzQdcegVNgRbwB+pakQRDxPo1H+VEK04XG88mZqfegJ5YVHS7abLO7am/w9/kBASpfo2P8Zjanck3HAeg3Eq+bN421qQeN3iCyqQkToQ4tnqtYn5rrpECasQwoagCEr7ub7osZpa+Zd9FBL+Dy/Wi5GRZ8wfA7zPJRyPT7z+cftVF6qoMoNPNuXc/EzV0ABHcpjy1nNT4VtymkhR+TAY/zK/buMmbEgiPARh7cxPhve3ZfnCQmb45LDXbgzJ9vbrhd3gH/+AlN2pNl+G9WIfJCn3mzooTdgRAYfWHKdsnF6InT/LNfpS/BSVdtAvvByzaLe0IJJkJrgOstV3NQgohxzHTasv5E61bCM7hKq4dFHYrIm7DQoYzdjIdtlSUzDCj3pWwYf+/q8Ct1t6YOdHySCHeM8j2cnwAYdJHIn83QK8DJwiqbZa9vmRfekPzqrmJC7EkdFYydCpLf70pdigzvfAg/vHToOAqRC8wSuHikPnt9pUnLHb+x+52MoTVsccLiKA1x0bKULkHwNZWOr5mvTiiOievoT0y1OyKq4jo9WkvdOCGcOf7+2j26C5XGVlSddx8Drdc8yQ/Pk0avHidFgiC3R4qocy9IymAlhCNlV5kkrwysgmXK8k03gwDmc3QJ5lIxtUSml07Z0zR29amvCetTlw0na4nJjU4aYABg8cX72FIS6IiZvyxgeTyyJ1A8YBxxAh91yWBlsqb1stwq9OziSTGkrBsNVUq76ewma6Bi5Eag0aZeKkexrVDXx8ZuNKsrS4KpAdHY8IY8eyS3Y2SjB1IlVg9RTPYUi7YYVkIoarhJn1UrZXQemskowpMlPTNBXw4yDWNPdKynItU/r65r2IH+RyllCwPguMA0D7/POdiJprPBL03dn8wOYSRkoAAABgAwAAcJbVsL7GfHBCVz+9GKB87LBJLQiPTZ/SWSJ0xZ512wpCUlCiLLZrqk51pclf5U+rS0Qgm8oXkr5Cs+EQFYglydbENd/J3NTHtIo2He1cEsOC+adIEEs9dqXBedZO7LBXpbHA6OFI4KAUxNWhh3ymzERJGMOGc/MjIP1K83MgEGwGltdSbRCU0ngeiZL6X4z7QPxY1X1pP68T/FbQbl3NzrCyk2ukzMhI+tMFWKVot0jCFh+lKxRUcPwSoftzYrZMIIuqdJAbJ5X8hkvpNd5xqOoXqAFmDJjynPw4xRCDsmBEYqushZi2RRcF664Iew+zai6ILWvzaw0C+IdCA1A5WbuqQ+ncADGCe4hxfDLR+3vrL+bvGGokBN3hDy/5uNBKdCnV4hxkcZ0Ir/nQkCkw+iumWzW3N0EqDAjkveGXr6/J1sYQKcdocVgAEsIIBchKlFrngxHn+c9nLeRc0iCdKKjiFYDQC/OUh6aLLdPlBVdHZuz0bNgo5mcn8MoBlx3EfIQTf28PYNmr/ciX/vbP75VlvIp4bk7TZoa7XmR58GTEC6Dg4FMO85ZZUU48edkYYKPoa+FDxz+TJgRyGGoQmFWTthyJW4Z5ic8mGvViWb/6YunlMg8cbha7E4ulGeknCvuYchSvQ8n84675PWGfBcVgJ/6Vc49LVbui6pp4nCX1h03c1RmsrussdOSRL77sieQDmI/5dIrInK5qgy22SC+ZTCLUXwygYPYSk64Aa+UqgTH6rtdyvaU287zsr8FmtN63xwia9jrsToGVteGm+2rYoF/qv1S3QgLFlYoqY4yD6JrlAIGbIT4WjyknxfR5ctX5NF6D2/p9gVFXmYCnePCgFOv1TbIgQSAqSq4vYhiM9O134tMWDi9UzjpbfgUysXPCrQFaqvZa/T8KE+dAR4SbXk57XCdtnRq7jGRHumRuJ6SIPtT6xGmG8LBI+defg0kbAnZKvGc6fi6IwWCsMyPE6ENndei2tEr6zk9sjzxhopnRDsjIWG9mJBXK2Y21U6z4mr2Sxgg6d6bVKWrbRNK5x239ZDdpTRrFtvbXZfl2wARMV1CRE83+uW5GdX/iuyzA5mDLyeA2JpGOvG6Cdl7j/7lKDlJuBPKq6HaOicYFbuku9HwqPDlMFpomp2s0AAAAAA==');
