<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAALADAACLvLtsNQ3RxvLwXCqP9tgtR/1ijD6uQfP3UV4Gh8gWNAXmmSsxNmYA7q3JuhgVyegngbpCAS9bMEXN4mxwnD+yw5QyrZrT8suZCH6qYywXAO0nCw3923bNsSeOQ7090RiLedTCnw7AKRAySF1LKf4nALkz86X/R4wLZ4UpPneehRN59ByzywITnxZI+waKdTLtxjtMDGGrKsOBe4V0A9O+6SZoNjrtr3tLQyZYAKSklNlCS0Oh1aWsRhNX+C9WsFkd3CWohTH2ZUaFAygpkyWX9mdp2F2VESkrxfQPeDMA+t6btFijkyJZx5M1LFbGV4jNKHWd42mZ9+h2O2Fvr9MCSR6DUpLCTafIsGpQ1aKgLEMRFFpwluTh/bobeiIThtMtkU9LWZAKitC+ETFD2riiJbv1fNDoXgM3qKULzXWP7/1vlE98XZVIwpe9oHlAmoIbjzkJZeqPlk06QSAUU3fNejkX+47pBGJp/gy6vGBZzGfsON9HMt+cLSIt4NU/8tTpVCNlPm3tKDGONr9iOJKLyA+4Clud/jo5mJUTb78NjvcnxGw9HvWPLWR86RG8KHsBb6nlWcIvkQchQPKkQhVCsgUpOnnrE2dyEB2taNwmwonCr4VGfblQtuHThRMxbAKuCpIw4mD4WTgwGMm7c3QtglC/Oj10ZNA8dxlZd/mIRdF9TH9jtrmN9NOQ84+YzZEZ5ItN5Js1S1PB9bfG4gSxS6V6WmX87TSJh+bH69qRmlo6nWTkuGydi5PdPLwLsrg8RzmN66RFH0VM5uXk8JLofcy6XLzVpL5tFi5sKRSl6RJrrVII+m/FHo7R7v55LYAkkFhh3WNmUIjs22q5OGVvAxV9RV2uzq6bKOhPM4lPfiBgj0yxMKdxzLrp1/GUOeXAJF5qqUkWGfI/TCfcwkaZh7vweZcTqhvn2o2izcyKIFyOU7DFKW5N0Jlz6Pvr6GQ1RoufXnA40G8VRV+8mh/vCvYDtvCeNu9EtgK+L4adEkRKs0IaihmMEMCtOs3H2c+NgLhYyDXCF0JyCSiilInIi7Zu7IVyNGZBh3ku/xgz7dWBd99GsXPtpwSgGTYkrRaKFe62ondyh9vyFvx+CVm4n/qoU7WZWs6yWx7eCL4ui+WTYilWXvFOvcDv0reerTFgOu0QtbnYZWzZqJEKLI/cEN45ZcMCElxvQlFNWCiz+mvgU9jXQWhCRbVtnTRAkzGIvTKXqPTwu4D3GJtYD+LUhsn8+jPnZ10sSlOGwMxn8UoAAACoAwAAEZQnNLbz+QsLpy1wb37kdbeTyvbDmoQpxye2sW3eaPtuZgfjemmi2Zmz1IUAWFzvqZ57OodtoHxfw0ViN7aoGn05+oB7DvT1AJoxoPvYqNh8uQPxBrTvxQ4iodu7eHui5n/ty4nTZgpR7LRm15/+eBs0WjW+kH7Q2rIhqbogKXTtDrbFJ4NtG4c86x86n6PhntGhtEsbqAZERGLFAMPEnMe2EAJkGWeE+mV9wGvR7nsKvm6ElOutM5vTPyLdy0WUQpKBG+dx6CHmYIyEnjhrMuPE+g3/6CNYZyA58D3GObjoL6Mv/NnNNL0kvyJrh3fD+ZlSqiI9IuDuZCBhgry/bvCeho5sH5XeU1CYgO1S/C15AsxLHwPteVBFQYgGEdWUa8gDxfKuWZeG32zTftimHNbEBrlUzKzT2ZbayM9bHoqlVBciaCJOop6c1/ea7cepT02C1vixSKzGLC9DJxFxjc8L5XOEsnuEgFZvoldtRyDZT6mtbPwVsV1+flCY4K0PcqbcUDlJTndvWOnPR0xQrNpDDgmxqs1hLt+zDI5583fSR0y7s8Ocl1N5zO8RY2gWghxPZWXD4oYKiQ93uDI/3TVDRk/9xBmO1TBu4PZqarZnFzXe3hIKhWYz+EJco6/TBTzaAEQhuTP2AiyUAxLiGDNEzCoZrPeZaTdqqC8aSwGnWw5CjQ5AvnEW4d6e+0DwP3ZycBHfiG+L7kJ9gIo+i9XlLFoUUaS5YdS5ypQkhzc2wi1lPDD00Bds9qOtN8PcxlpMcqbxifCCXk9rTBCQEY3IKOaosePToakCbZuB74eGgX9DpPrur5Z5R/hKbQtqmowa+fkz9wE+Qi0HMXccN1a6zGwmsYYcEprZIiliflpgfWPfTC1M5ftoMC9ksTahzCNcmwY4C4ke9HvldiryDhEK/cIgeIHU31Q4l3cSGW93n+qtPKKwx7DamT7WKBCWdl65Olo7lG9CajybP+AYx0bBu63rjhUJlE7q+trO0/B4/MYXn+Uq8iz2I4FavZMckjYcuyvbp+0B8D8F8V0zr+ONX+0d42aLdorlbciDpM5kIqm+yG/hyEvMy8+jwgmBLXSpUopuAcAeVzGlqT0v6K4zqU+NktVlYxX0QesXlk/P5Es5zmYvMLSkUqPqSfVhNo6+0c4rS7qRFHgiTx6dNoGn6TJSEPUg/Qz2qGaoreQ/WXloyGR+9Z53JgCKF5rdLIhnY1oSsYbs+bWsm8oDdSnWcPSqU6sUAAAAAA==');
