<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAANADAAAkW7CPSGS4bBMeVlOcIep7gCzUmX3aa1zCwcTAWS7XPoyyTeK/SfO8VC8lWiyh8/BViNiM9zckrmIAP5Mjq0t1kMn68FtE6uPGFXMFVYwL0BNNoUooZ7k+v9ImGGV0BfLJ7gn6HujV8FP3MpJNTMPSglI3gyjCLy9F504PUXIQqy22IS3Z710xkMh3Rj6I8Bhc2t7EUP8NT5b7sON1yyAVt0zd6bzeMAfqm1nQAvoS249wT/wOH1oj/0/I5H7gpI9OWN6qheCZ5IsmyCr4rk2f2B0ynk5OghgLRkbWKRT1Ai8DvjtNobfV9ilqBhbe7ALkHaSbpXUzzHbTpwEruVVqN5KDEaI+DIclBemopq/adV04SO8JXJkSPUbxTubS1SjmGdIGk0oSZHgfOxqF6jYsH94BDwuLMcy9ymx+wWhxlnf1g/tz4mM1LqaIKp8TjZiGLw7WiY0mzgUUMNep0QQaYoVI8AJNYWOTzWZplesZgPWlHKzG36KgfJtO2Kt/1S3cFBsG/CP0L8AML2wE/IzUA9HRIgY1Ah9C7Hu4ymRFm8ZFvbvXWfTX2rOe2heWyCn1rPYph/Z/TayhT2Ej4lvPy3YnvkrO477GU+i2NzqJDAtkn68iTq0nqbSqHbGs9ARozBttH3+b2B3RLgHM9T44KFEF4S/dnQ39ydwJyRMc0FvyUQSoF4hJt9djupqPxy2y4QiRAuOtKKZ3CE9SgDAVlFbkf/jMaIGazW1PhwQwjlBC3x+mxh0r7rv+exMFuFoMz6ujNmugXYH96wHfSbb/cf4ooU3Z+kC2g7n5gvpYUwjkfCu0AHuY78T0dPtNlpnf47PAtM5S9eqy9WYMcedYBcYc8vky/gGk9RzuK0vZXnKWY8G58PZAYfbamjIqVvqyl1kkrL0eq6oyjBRBSVBaWIB6TQb6MYkbgtSFx6C6Yyt6N6cYDFW/6IC/INnKtCknyEmT0dI3K1mkUfF3f1C13Dhk8K/zwWhwPdOjsDl2GXJXnum/z+Z7oTuEf5gpj9uZp2y/KmDhg2y6U1nv02difuAMhg1/uk5T2zhyr+OwjUxV7C+oqODQxvQJG4LhCvQWbD0H/rY+QDjrJYbgOYMj257MA1gXmqFzW8qAxzdOWat39c9Uz/faXDxiKq01AniTkhkWGzTT9eg9IL2BRbnrxkalTGhDdqlboPd1CVcorFszTVpbSvQPDvJiHxEyNykdPsmnYvluvDOhhpfi40vhp/sH4C+9haHopS5vsYk0wghN5hNUJplsugGHS30LjPgLikdXx0mmOX6PZLHTN1u5SgAAAMADAAAz+6mLuoM4XnajQHNEsGoUE/cpoq4AfLXMBUYk6785JxODnAtfd/e8q6BTcBjWGPZ/2Of/dmtfqqNz5O6Li0eoDIdcCPj+/V5jTM5ovqrXpM/l/u9TajfaX7PfrwrYp17IZ2YcKd9s5SgDjRAuzVM1sw4PbYQlkxJDD23RFrUo6PFgOeG1MAZzgW0BzKAR3aP+qxXoLOz1GpB+DiZN0i97NkdKDkBjbw+mezEJ6siQR7mtG4ansmTilH70oLXbX3CMefmKYBBbsAiO7fdtx4D1gF+PAlNuMIHIBvR/S1T79X84GRTiKOVaYcmdawh8r3nSiOLPlIulSNDbkm/+xA3C9C+w7/ApqdI+eLxOBizQdTixw2uznMjeJK9fnDQ8VgFP6lVadTE32iO/JPOgOOLh6hb+BThNaAd6haLvrOpo5jC+XJ6PM0PGWzQNQfHAmi6dQpCvtFl0+3aJSaNOCQ27oGuxDvU39DWrUwpHbZh2z/9pZwVMbANcedexDxRrhBkKcf0+/qChSq13sxkUE2cYH8z7hvMkwhFc3AvVzJW+a8UWCaNoCT7ZwlQA0b1kf3obfEdnpZ4vXwWYk/38yPuWbiBDdzC8divrZQ1MBhvO64d8QuYhKagftnINYF+22yML41UPJI81cVBNu2TFcaYRJq0SxyV6TqxsJEnILTtXQgwK6yKhFsxYwy8CXrgkJ+3NpgaI08bHCi5eyMFqbzd9U8ps34BoD2TO/JFWiWzbUceyUy3jTWzdl6AOm9u8kKZXMBJZxrH/Jxgb4cYNc8EhNYOCWiTrPT0srO9D9+3lRXsidWK1y9TPp2H6gKe3GMvyAxrET2SUHwi6nN6OE2hzvDoCsK838KBZE6KDzj65Cf2XSx50qvkr/WZN1asehPSTkT28aoLviHwHomuApj7RT8XHhzCJMHNwG0PbIdVNdNgJUU+JGpzDflvLL1kOTuVHGPFDz/MBKVe9EN0d5FXSD4I4VB4i+HeqmHMbmMPOqhXZOVP+RmgPbrRupWSpA4IRCZO5miwfU1mYYHU97x7YdIlxwb+6o4jEph8CLDwmd1Ki+qfP+SKwcmtz5wNdZHDCyVW4cJdNnHKdc9NIeU4PF+xkiJGwNWpDQE5W/7SsS/cv74XoBJEm7sdAWEp2jnk+Lp/DClCGTXBOThgVAuos5Im1D+/MT+FqRIIDUE3KUYOcmdDAIhMnQ+TYcKUJLA0nx2Fep9lzXQJdmg0MmE8v5SqyTpWxOjDYP7vmGa+gYZCGvAXCovJGcQkAArzIhwYAAAAA');
