<?php ?><?php
/* WARNING: This file is protected by copyright law. To reverse engineer or decode this file is strictly prohibited.
Written by James Robshaw.
© ProExe Limited. All Rights Reserved.
URL: www.proexe.net
Email: support@proexe.net
Encoded: Sun Jan 03 14:03:54 2021
 _____           ______         
|  __ \         |  ____|         
| |__) | __ ___ | |__  __  _____ 
|  ___/ '__/ _ \|  __| \ \/ / _ \
| |   | | | (_) | |____ >  <  __/
|_|   |_|  \___/|______/_/\_\___|

LL API version v1.64 */
if(!function_exists('sg_error_handler')){$sg_err_h_path = join(DIRECTORY_SEPARATOR,array($_SERVER['DOCUMENT_ROOT'],'locklizard','api','lib','sg_error_handler.php'));require_once $sg_err_h_path;}
?><?php
if(!function_exists('sg_load')){$__v=phpversion();$__x=explode('.',$__v);$__v2=$__x[0].'.'.(int)$__x[1];$__u=strtolower(substr(php_uname(),0,3));$__ts=(@constant('PHP_ZTS') || @constant('ZEND_THREAD_SAFE')?'ts':'');$__f=$__f0='ixed.'.$__v2.$__ts.'.'.$__u;$__ff=$__ff0='ixed.'.$__v2.'.'.(int)$__x[2].$__ts.'.'.$__u;$__ed=@ini_get('extension_dir');$__e=$__e0=@realpath($__ed);$__dl=function_exists('dl') && function_exists('file_exists') && @ini_get('enable_dl') && !@ini_get('safe_mode');if($__dl && $__e && version_compare($__v,'5.2.5','<') && function_exists('getcwd') && function_exists('dirname')){$__d=$__d0=getcwd();if(@$__d[1]==':') {$__d=str_replace('\\','/',substr($__d,2));$__e=str_replace('\\','/',substr($__e,2));}$__e.=($__h=str_repeat('/..',substr_count($__e,'/')));$__f='/ixed/'.$__f0;$__ff='/ixed/'.$__ff0;while(!file_exists($__e.$__d.$__ff) && !file_exists($__e.$__d.$__f) && strlen($__d)>1){$__d=dirname($__d);}if(file_exists($__e.$__d.$__ff)) dl($__h.$__d.$__ff); else if(file_exists($__e.$__d.$__f)) dl($__h.$__d.$__f);}if(!function_exists('sg_load') && $__dl && $__e0){if(file_exists($__e0.'/'.$__ff0)) dl($__ff0); else if(file_exists($__e0.'/'.$__f0)) dl($__f0);}if(!function_exists('sg_load')){$__ixedurl='http://www.sourceguardian.com/loaders/download.php?php_v='.urlencode($__v).'&php_ts='.($__ts?'1':'0').'&php_is='.@constant('PHP_INT_SIZE').'&os_s='.urlencode(php_uname('s')).'&os_r='.urlencode(php_uname('r')).'&os_m='.urlencode(php_uname('m')); ?><?php
echo 'This file is protected. Please contact <a href="mailto:SourceGuardian@proexe.net">ProExe</a> with the web address of the page that has generated this error.<br />';
?><?php
exit();}}return sg_load('21D87001A6B878ACAAQAAAAXAAAABKgAAACABAAAAAAAAAD/I3XhxLbg78/MvnIYKYbo7JbflbC+UORlQte+M1o7eSovpVpQ6GbHl5vqOP1aCMX5KgzfJVY9xYr2ltiVqzY8m3bnXKsYI1Uso5355HjWpcFFGabpgKWwvZ1M3OVdNyBNkkEIqqKMIDabrfOCMktHS9djnO8ezJMzQu4J7ZBBU6ke04hC5VWtj8f8m0bqNpY0LbWK2rF6q8P3QkrcwQ0PJojqLnJfYoQMSQAAAMADAAAf3hxnCuvXscqV6N312TCjYVWIQKLmHaQM+i0iTplTJghyDAoJYzL0YDCvb0qv/2K8ALgbJecidbpTUYqP+5umSD5mr/CxUYpX0G6PA5gLWC33zd4ZWrJQsuSg6O+zQd3xZIy/Qa+9Bdp6Lmdscw9grag5r+2k4v9p30898wR32n+cDO/36Crl2K2lxsLYbGJHL3lXGaHIoa33ZHaxSuDo8YL6q/4WQuLyKJe4iTeGyhqGJ6vB9feMTU7d+ZnvkU0UfooyroG0vn+PcxAg5GtluZQ/Ov9y7vk5wiYv+k23xskVnqFhYXyinkB9dTwokXAYYI2bYQjtcdD+zm9nrUt9GieFhmYneTX9/JiNip04g6r34kAyITkVcZXzpI19QyK4+WdpT+vUl3iHiW/MRcJv21NzccAeLibKA8OA3IvvpEECMvR95UJbFAQaO6rNNyWQJpvC0hyl5to8q13W3Mq6wmJHBIaPCrFtrcksjV9Qv5pxuma5sMgiAWXgnOlQjF9fQyv0wvHM8QmH+8N2LEcbM6KkWFKNIYDZ+mU9+giskZxK8aZc1I7nuBLGZb7nrEpG0dtWGMXcpETrPU0mDQOlVrpMpICt/WTEujm/680etS7gr1bz4jnNfsvL0QQB4fT1mZsPnXX9fSbUN6I2CB9P3d39TYjc/PomhvoWWTA6vXQsKXKUvrRW2kof2cULtce2B3vuMNFUFKGjzpapwbMR63n8lKzsC/Pvi9VBltc6NpG0MVXKAYmcc6Lb5MQTpUiaksHoFVCDyWNZ2rvUy9i1KPWUEDFLL8gCNhwSKq20G9vZtrT2l+R5qdpWiBEmn7XZ3/0K1Ijq4NPnAuk4KGQiP5wqUnqPRqZhBtprQ+c+UJYle2nftjet1Xt3YDwq+LKHtsaj7WJbdWVwUVB1aNHZi2itVlah1vOfxq0+gSff7Wnz2mwKvdlfLqjXxP7aDUKkcByNnLvqoohxGhyi8292YLbVhxtSl5yQKHPVZuQLogzzPwWENjtMBHK2dNsnlbq0Ngywn1DG/TuhKylII3DI1rGZU5sXYe3T9yG7QiIK2TAvLhbVoZTgWU6LahQbWuBF3U50MDVnNfndmy7sThWS7GucZtGvX90c0iR7MHkphIFTB6/xdqgKbum6aUXWpt4zEiTMktYcSRAfxTFMbEH0BXPrZTm3qC87bmJ1TpGqcgUEsKoqGOJuOwDa7jI9t5PxPTBUbq0ZdDHfu6KNMvsDjBnjeRo9IiM08h2CdYPPj9n8gMtHuPoPNpogej6v7y5KAAAAuAMAAGOQL8kfrSfHKkmOJcOevJUgz5i+4QaybMAfcn1v8XoAcIvO0SDDGvZoJK5GVT0N8rzip+C4V609m7Zp+AkKazm+R/6vFH7m6MFWgQLFAD3PUk898kvriehk1LAgvWcuSJxwLXxNnuCxwgAl8fDLbC5wYo5Owrg8VgFaMhDOU7wuCxd7tbSe0hVAhU9vfS+gmExH/xZlQS2kyHgbwuhyL1+QageygNcblRD0yumBhZZCU6gTrifKJ4Hyp8yh6owxtZ1PIYwI8kDRSJtzeOElRM8ypww8d5QTdlrEegzm4YSvhOEZuUnGGccfdMcZFlvGZzrLM4SPRVZXnaKxO9ibbTMxCQLuXWIVp5T9TUaAaNuwSAVs7JrINRxSPB8RQR0Tvb5r86QoUNinEs/+BoxQ3rxAVDDOTYy06XwUWCOoum38PbJqBaDmdkbz+foqL3jY6phOqQk61uoCQ1SxHUUujbtAxRrRCBNBaNX59ZXr6TstFfj0exthxcDb2qAzGK/Vqp1hxNs9TDIiIhBRcLmvMnkQFxawhBlR+AjLeLOPBbNRB1/j5ni0sa/YC9y03+a55TgdExph+XcfxMOOshdjY/4ErRYSll/nUQC1Rn8rm5sNrvS23Y9dRrfZvT7CROpBzxpKzq7CLaG9jm6hL4d/N3FI32yxv3rMA2nvaKb8mdfqP1Ih1C8OotuiTPF5jdyGGsyANecZoNmGhvpi6/wt4Cs1pQkgAZbD1wH4B9MLLCBxpAJyx7WKFoa4wjNGpWpw+JbaRFCFS4jyYiSxuaDyO9BJKJBQ0snfnSGPiBn/hgSDvRrOvjucGN5rvDpggljiwLg1L/Jdut3sEdqBeqnVTVz9h5JlGrStyBwuNqKQoBqJfD0OwDBn6uNqNEjakk9acNat83ZAzzAnblPsyVROn+DGNFT5PsrpPDHMv5ULJxDv6RHGhiIMCoz2fgjJkbwa7vPw6UwKzYARMWZ4TqhXqDP7XmQrHx7oGpNjcauu4+lKJIOU2QhbrWMXljoXo3joEjGZUb/+hs6mlhqsnaYHQuDxRcoQtOnma0WMA2WiiaUyNGiqMiM8d6qAmv8lchMasiRS19Xea9OsjhxPzzmg5jaolTqfv0iYXCUx1EvmN0ctU+jXh1kDJZpn6AebL4dEV8laB5fU4v/I7UNL1X9AmDr58d+4p/qRUj4aakDGuD/6v+i0slxTWoYyfAsWqMgzmUnb0X2VL8sSQbc6OMEDZDOIcwwTMekeu3+K5DtWySrJtg5y40g1uWgAAAAA');
